### ISSUE TITLE
PHP and PLP in IRQ

### ISSUE THREAD

**Issue by weierstrass1** [VitorVilela7/SA1-Pack#32]
I was reading the IRQ of SA-1's pack and It doesn't use PHP at the start and PLP at the end of IRQ Handler, I think this could be an issue because if IRQ is executed in some kinds of escenaries could produce crashes or logic issues.

**Comment by VitorVilela7** [comment]
PHP and PLP are not needed for IRQ and NMI vectors because the processor state is already backed up when such interrupts occur and the state is automatically restored by an RTI. RTI gets from the stack the 24-bit return address + the processor flags (I don't recall in which order but the data is that). No action needed.
